core/urls.py
from django.urls import path
from .views import (
    item_list_view,
    item_detail_view,
    order_summary_view,
    checkout,
    add_to_cart,
    remove_from_cart,
)

app_name = 'core'

urlpatterns = [
    path('', item_list_view.as_view(), name='index'),
    path('home/', item_list_view.as_view(), name='index'),
    path('items/', item_list_view.as_view(), name='items'),
    path('order-summary/', order_summary_view.as_view(), name='order-summary'),
    path('item/<slug>/', item_detail_view.as_view(), name='item'),
    path('checkout/', checkout, name='checkout'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart')
]

djangotutorial/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from lorem_text import lorem


CATEGORY_CHOICES = (
    ('S', 'shirt'),
    ('SW', 'sport wear'),
    ('OW', 'outwear')
)

BADGES_CHOICES = (
    ('E', 'eco'),
    ('B', 'bestSeller'),
    ('N', 'new'),
    ('D', 'discount')
)


class Item(models.Model):
    ''' This is represents the items that you can purchase in the Shop '''

    title = models.CharField(_("title of item in store"), max_length=50)
    price = models.FloatField(_("price of item in store"), default=0.0)
    discount = models.FloatField(_("discount price of item in store"), blank=True, null=True)
    category = models.CharField(_("category of item in store"),
                                choices=CATEGORY_CHOICES, max_length=2,
                                default='S')
    badge = models.CharField(_("label of item in store"),
                             choices=BADGES_CHOICES, max_length=1,
                             default='N')
    slug = models.SlugField(_("slug of item in store"), default="new_product")
    description = models.TextField(_("description of item in store"), default=lorem.paragraph())

    def __str__(self) -> str:
        return self.title

    def discount_price(self) -> float:
        if self.discount is not None:
            return self.discount
        return 0.0

    def get_absolute_url(self) -> str:
        return reverse("core:item", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self) -> str:
        return reverse("core:add-to-cart", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self) -> str:
        return reverse("core:remove-from-cart", kwargs={"slug": self.slug})


class OrderItem(models.Model):
    ''' This represents one of the items added to Cart '''
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             verbose_name=_("user who added the item the order"),
                             default=User.objects.get(username="admin").pk)
    ordered = models.BooleanField(_("checked if item is part of an order that is checked out"),
                                  default=False)
    item = models.ForeignKey(Item,
                             on_delete=models.CASCADE,
                             verbose_name=_("item selected in the store"))
    quantity = models.IntegerField(_("quantity of item in cart"), default=1)

    def get_total_item_price(self) -> float:
        return self.quantity * self.item.price

    def get_total_item_discount_price(self) -> float:
        return self.quantity * self.item.discount_price()
    
    def get_amount_saved(self) -> float:
        return self.quantity * self.item.discount_price()

    def __str__(self) -> str:
        return f"{self.quantity} of {self.item.title}"


class Order(models.Model):
    ''' This links all the order items to an Order '''
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             verbose_name=_("user who created the order"))
    items = models.ManyToManyField(OrderItem,
                                   verbose_name=_("items added to cart"))
    start_date = models.DateTimeField(_("moment the order was created"),
                                      auto_now=True)
    ordered_date = models.DateTimeField(_("moment the order is checked out"),
                                        auto_now=False, auto_now_add=False)
    ordered = models.BooleanField(_("checked if order is completed and checked out"),
                                  default=False)

    def __str__(self) -> str:
        return f"{self.user.username} - {self.start_date}"

templates/base/carousel.html
{% load static %}

<!-- carousel -->
<div
  id="carouselExampleCaptions"
  class="carousel slide carousel-fade"
  data-mdb-ride="carousel"
>
  <div class="carousel-indicators">
    <button
      type="button"
      data-mdb-target="#carouselExampleCaptions"
      data-mdb-slide-to="0"
      class="active"
      aria-current="true"
      aria-label="Slide 1"
    ></button>
    <button
      type="button"
      data-mdb-target="#carouselExampleCaptions"
      data-mdb-slide-to="1"
      aria-label="Slide 2"
    ></button>
    <button
      type="button"
      data-mdb-target="#carouselExampleCaptions"
      data-mdb-slide-to="2"
      aria-label="Slide 3"
    ></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img
        src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg"
        class="d-block w-100"
        alt="Wild Landscape"
      />
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
      <div class="carousel-caption d-none d-sm-block mb-5">
        <h1 class="mb-4">
          <strong>Learn Bootstrap 5 with MDB</strong>
        </h1>

        <p>
          <strong>Best & free guide of responsive web design</strong>
        </p>

        <p class="mb-4 d-none d-md-block">
          <strong
            >The most comprehensive tutorial for the Bootstrap 5. Loved by over
            3 000 000 users. Video and written versions available. Create your
            own, stunning website.</strong
          >
        </p>

        <a
          target="_blank"
          href="https://mdbootstrap.com/education/bootstrap/"
          class="btn btn-outline-white btn-lg"
          >Start free tutorial
          <i class="fas fa-graduation-cap ms-2"></i>
        </a>
      </div>
    </div>
    <div class="carousel-item">
      <img
        src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg"
        class="d-block w-100"
        alt="Camera"
      />
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
      <div class="carousel-caption d-none d-md-block mb-5">
        <h1 class="mb-4">
          <strong>Learn Bootstrap 5 with MDB</strong>
        </h1>

        <p>
          <strong>Best & free guide of responsive web design</strong>
        </p>

        <p class="mb-4 d-none d-md-block">
          <strong
            >The most comprehensive tutorial for the Bootstrap 5. Loved by over
            3 000 000 users. Video and written versions available. Create your
            own, stunning website.</strong
          >
        </p>

        <a
          target="_blank"
          href="https://mdbootstrap.com/education/bootstrap/"
          class="btn btn-outline-white btn-lg"
          >Start free tutorial
          <i class="fas fa-graduation-cap ms-2"></i>
        </a>
      </div>
    </div>
    <div class="carousel-item">
      <img
        src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg"
        class="d-block w-100"
        alt="Exotic Fruits"
      />
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
      <div class="carousel-caption d-none d-md-block mb-5">
        <h1 class="mb-4">
          <strong>Learn Bootstrap 5 with MDB</strong>
        </h1>

        <p>
          <strong>Best & free guide of responsive web design</strong>
        </p>

        <p class="mb-4 d-none d-md-block">
          <strong
            >The most comprehensive tutorial for the Bootstrap 5. Loved by over
            3 000 000 users. Video and written versions available. Create your
            own, stunning website.</strong
          >
        </p>

        <a
          target="_blank"
          href="https://mdbootstrap.com/education/bootstrap/"
          class="btn btn-outline-white btn-lg"
          >Start free tutorial
          <i class="fas fa-graduation-cap ms-2"></i>
        </a>
      </div>
    </div>
  </div>
  <button
    class="carousel-control-prev"
    type="button"
    data-mdb-target="#carouselExampleCaptions"
    data-mdb-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button
    class="carousel-control-next"
    type="button"
    data-mdb-target="#carouselExampleCaptions"
    data-mdb-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

templates/base/extra_body.html
{% load static %}

<!-- MDB -->
<script type="text/javascript" src=" {% static 'js/mdb.min.js' %} "></script>
<!-- Custom scripts -->
<script type="text/javascript" src=" {% static 'js/script.js' %} "></script>

{% block custom_extra_body %} {% endblock %}

templates/base/extra_head.html
{% load static %}

<!-- Font Awesome -->
<link
  rel="stylesheet"
  href="https://use.fontawesome.com/releases/v5.11.2/css/all.css"
/>

<!-- Google Fonts Roboto -->
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
/>

<!-- Bootstrap 5 -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

<!-- MDB -->
<link rel="stylesheet" href=" {% static 'css/mdb.min.css' %} " />
<!-- Custom styles -->
<link rel="stylesheet" href=" {% static 'css/style.css' %} " />

{% block custom_extra_head %} {% endblock %}

templates/base/footer.html
{% load static %}

<footer class="text-center text-white mt-4" style="background-color: #607d8b">
  <!--Call to action-->
  {% comment %} <div class="pt-4 pb-2">
    <a
      class="btn btn-outline-white footer-cta mx-2"
      href="https://mdbootstrap.com/docs/jquery/getting-started/download/"
      target="_blank"
      role="button"
      >Download MDB
      <i class="fas fa-download ms-2"></i>
    </a>
    <a
      class="btn btn-outline-white footer-cta mx-2"
      href="https://mdbootstrap.com/education/bootstrap/"
      target="_blank"
      role="button"
      >Start free tutorial
      <i class="fas fa-graduation-cap ms-2"></i>
    </a>
  </div> {% endcomment %}
  <!--/.Call to action-->

  <hr class="text-dark" />

  <div class="container">
    <!-- Section: Social media -->
    <section class="mb-3">
      <!-- Facebook -->
      <a
        class="btn-link btn-floating btn-lg text-white"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn-link btn-floating btn-lg text-white"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn-link btn-floating btn-lg text-white"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn-link btn-floating btn-lg text-white"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- YouTube -->
      <a
        class="btn-link btn-floating btn-lg text-white"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-youtube"></i
      ></a>
      <!-- Github -->
      <a
        class="btn-link btn-floating btn-lg text-white"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div
    class="text-center p-3"
    style="background-color: rgba(0, 0, 0, 0.2); text-color: #e0e0e0"
  >
    © 2022 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

templates/base/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %} {% endblock %}
  </head>
  <body>
    {% block navbar %} {% endblock %}
    {% block messages %} {% endblock %}
    {% block carousel %} {% endblock %} 
    {% block main %} {% endblock %} 
    {% block footer %} {% endblock %}
    {% block extra_body %} {% endblock %}
  </body>
</html>

templates/base/main.html
{% load static %}

<!--Main layout-->
<main>
  <div class="container">

    <!-- Navbar -->
    <nav
      class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2"
      style="background-color: #607d8b"
    >
      <!-- Container wrapper -->
      <div class="container-fluid">
        <!-- Navbar brand -->
        <a class="navbar-brand" href="#">Categories:</a>

        <!-- Toggle button -->
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarSupportedContent2"
          aria-controls="navbarSupportedContent2"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent2">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <!-- Link -->
            <li class="nav-item acitve">
              <a class="nav-link text-white" href="#">All</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="#">Outwears</a>
            </li>
          </ul>

          <!-- Search -->
          <form class="w-auto py-1" style="max-width: 12rem">
            <input
              type="search"
              class="form-control rounded-0"
              placeholder="Search"
              aria-label="Search"
            />
          </form>
        </div>
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->

    <!-- Products -->
    <section>
      <div class="text-center">

        <div class="row">

          {% for item in object_list %}
            <div class="col-lg-3 col-md-6 mb-4">
              <div class="card">
                <div
                  class="bg-image hover-zoom ripple"
                  data-mdb-ripple-color="light"
                >
                  <img
                    src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                    class="w-100"
                  />
                  <a href="{{item.get_absolute_url}}">
                    <div class="mask">
                      <div
                        class="d-flex justify-content-start align-items-end h-100"
                      >
                        <h5>
                          <span class="badge {{item.get_badge_display}}-badge ms-2">NEW</span>
                        </h5>
                      </div>
                    </div>
                    <div class="hover-overlay">
                      <div
                        class="mask"
                        style="background-color: rgba(251, 251, 251, 0.15)"
                      ></div>
                    </div>
                  </a>
                </div>
                <div class="card-body">
                  <a href="{{item.get_absolute_url}}" class="text-reset">
                    <h5 class="card-title mb-2"> {{item.title}} </h5>
                  </a>
                  <a href="" class="text-reset">
                    <p>{{item.get_category_display}}</p>
                  </a>
                  <h6 class="mb-3 price">
                    {% if item.discount %}
                      <s>{{item.price}}</s><strong class="ms-2 sale">{{item.discount}}</strong>
                    {% else %}
                      {{item.price}}
                    {% endif %}
                  </h6>
                </div>
              </div>
            </div>
          {% endfor %}
          
        </div>


      </div>

    </section>
    <!-- Products -->

    {% block pagination %} 
      {% include 'base/pagination.html' %} 
    {% endblock %} 
  
  </div>
</main>
<!--Main layout-->

templates/base/messages.html
{% load static %}

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>


<!-- Django messages -->
<div class="mt-5 pt-4">
  {% if messages %}
    {% for message in messages %}
    <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} d-flex align-items-center alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
        <div>{{ message }}</div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
    {% endfor %}
  {% endif %}
</div>
<!-- Django messages -->

templates/base/navbar.html
{% load static %}

{% load cart_template_tags %}

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent1"
      aria-controls="navbarSupportedContent1"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent1">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-sm-0" href="{% url 'core:index' %}">
        <img
          src="{% static 'img/logo.png' %}"
          height="20"
          alt="djecommerce Logo"
          loading="lazy"
        />
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% comment %} <li class="nav-item active">
          <a class="nav-link" href="{% url 'core:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:items' %}">products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:checkout' %}">checkout</a>
        </li> {% endcomment %}
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <!-- Cart Icon -->
      {% if request.user.is_authenticated %}
        <a class="nav-link me-3" href="#">
          <i class="fas fa-shopping-cart"></i>
          <span class="badge rounded-pill badge-notification bg-danger"> {{ request.user|cart_items_count }} </span>
          <span class="clearfix d-none d-sm-inline-block ms-2"> Cart </span>
        </a>
        <!-- Social Icons -->
        <a class="nav-link me-3" href="#">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a class="nav-link me-3" href="#">
          <i class="fab fa-twitter"></i>
        </a>
        <a class="nav-link me-3" href="{% url 'account_logout' %}">
          <span class="clearfix d-none d-sm-inline-block">logout</span>
        </a>
      {% else %}
        <a class="nav-link me-3" href="{% url 'account_login' %}">
          <span class="clearfix d-none d-sm-inline-block">login</span>
        </a>
        <a class="nav-link me-3" href="{% url 'account_signup' %}">
          <span class="clearfix d-none d-sm-inline-block">signup</span>
        </a>
      {% endif %}
    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

templates/base/pagination.html
{% load static %}

<!-- Pagination -->
{% if is_paginated %}
  <nav
    aria-label="Page navigation example"
    class="d-flex justify-content-center mt-3"
  >
    <ul class="pagination pg-blue">
      
      {% if page_obj.has_previous %}
        <li class="page-item disabled">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
      {% endif %}

      {% for page_number in page_obj.paginator.get_elided_page_range %}

        {% if page_number == page_obj.paginator.ELLIPSIS %}

          <li class="page-item">
            {{page_number}}
          </li>

        {% else %}

          <li class="page-item {% if page_number == page_obj.number %} active {% endif %}">
            <a class="page-link {% if page_number == page_obj.number %}current{% endif %}" 
              href="?page={{page_number}}">
                {{page_number}}
                {% if page_number == page_obj.number %} <span class="sr-only">(current)</span>{% endif %}
            </a>
          </li>
          
        {% endif %}
      {% endfor %}
      
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      {% endif %}
    
    </ul>
  </nav>
{% endif %}
<!-- Pagination -->